# Generated by Django 5.1.15 on 2026-09-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_organization'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='projects', to='people.organization'),
        ),
    ]
