# Generated by Django 5.1.15 on 2026-08-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='safe_to_spend_horizon_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='safe_to_spend_reserve',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
