# Generated by Django 5.1.15 on 2026-08-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_safe_to_spend_horizon_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auto_lock_minutes',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
