# Generated by Django 5.1.15 on 2026-09-23 15:38

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_auto_lock_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='enabled_modules',
            field=models.JSONField(default=apps.core.models.default_enabled_modules),
        ),
    ]
