# Generated by Django 5.1.15 on 2026-08-25 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
        ('writing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focus_sessions', to='writing.book'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='domain',
            field=models.CharField(choices=[('school', 'School'), ('project', 'Project'), ('business', 'Business'), ('personal', 'Personal'), ('writing', 'Writing'), ('other', 'Other')], db_index=True, default='other', max_length=10),
        ),
    ]
