# Generated by Django 5.1.15 on 2026-09-05 15:39

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('context', models.CharField(choices=[('personal', 'Personal'), ('business', 'Business'), ('shared', 'Shared'), ('other', 'Other')], default='personal', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['context', 'name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='context',
            field=models.CharField(choices=[('personal', 'Personal'), ('business', 'Business'), ('both', 'Both')], default='both', max_length=10),
        ),
    ]
