# Generated by Django 5.1.15 on 2026-09-05 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_fund_category_archived_category_context'),
        ('people', '0002_organization'),
        ('projects', '0002_project_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringcommitment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_commitments', to='people.organization'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='people.organization'),
        ),
        migrations.AddField(
            model_name='fund',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funds', to='projects.project'),
        ),
        migrations.AddField(
            model_name='recurringcommitment',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_commitments', to='finance.fund'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.fund'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='from_fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_transfers_out', to='finance.fund'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='to_fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_transfers_in', to='finance.fund'),
        ),
    ]
