# Generated by Django 5.1.15 on 2026-08-25 09:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('entity_type', models.CharField(choices=[('transaction', 'Transaction'), ('journal_entry', 'Journal Entry'), ('chapter', 'Writing Chapter'), ('study_session', 'Study Session')], max_length=30)),
                ('entity_id', models.UUIDField()),
                ('local_data', models.JSONField(default=dict)),
                ('server_version', models.PositiveIntegerField()),
                ('local_version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved_local', 'Kept Local'), ('resolved_server', 'Kept Mac'), ('resolved_both', 'Kept Both')], db_index=True, default='pending', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_conflicts', to='devices.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
