# Generated by Django 5.1.15 on 2026-09-05 15:39

import apps.people.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_auto_lock_minutes'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=150)),
                ('website', models.URLField(blank=True, default='')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('category', models.CharField(choices=[('saas', 'SaaS / Software'), ('hosting', 'Hosting / Infrastructure'), ('bank', 'Bank'), ('telecom', 'Telecom / Internet'), ('school', 'School / University'), ('landlord', 'Landlord'), ('supplier', 'Supplier'), ('client_org', 'Client Organization'), ('government', 'Government / Administration'), ('other', 'Other')], default='other', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('relationship_types', models.JSONField(blank=True, default=list)),
                ('archived', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(blank=True, related_name='organizations', to='core.tag')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(apps.people.models.RelationshipLabelMixin, models.Model),
        ),
    ]
