# Generated by Django 5.1.15 on 2026-08-24 00:01

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_profile_safe_to_spend_horizon_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('mood', models.CharField(blank=True, choices=[('great', 'Great'), ('good', 'Good'), ('okay', 'Okay'), ('low', 'Low'), ('rough', 'Rough')], default='', max_length=10)),
                ('tags', models.ManyToManyField(blank=True, related_name='journal_entries', to='core.tag')),
            ],
            options={
                'verbose_name_plural': 'journal entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
